platform :ios, '10.0'
use_frameworks!

workspace 'ProjectSample'

target 'ProjectSample' do
  project 'ProjectSample.xcodeproj'

  pod 'AFNetworking', '3.2.1'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'MBProgressHUD'
  pod 'Masonry'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'CocoaLumberjack'
  pod 'Realm'
  pod 'SnapKit'
  pod 'Kingfisher'
end

target 'ModuleSample' do
  project '../ModuleSample/ModuleSample.xcodeproj'

  pod 'CocoaLumberjack'
  pod 'Realm'
  pod 'SnapKit'
  pod 'Kingfisher'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        if defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
        end

        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      elsif config.name == 'Release'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
      end

      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
