platform :ios, '10.0'

workspace 'PodSample'

target 'PodSample' do
  project 'PodSample.xcodeproj'

  pod 'AFNetworking', '4.0.1'
  pod 'SDWebImage', '5.10.0'
  pod 'Alamofire', '5.4.0'
  pod 'MBProgressHUD', '1.2.0'
  pod 'SwiftyJSON', '5.0.0'
  pod 'CocoaLumberjack', '3.7.0', :modular_headers => true
  pod 'Realm', '10.4.0', :modular_headers => true
  pod 'SnapKit', '5.0.1', :modular_headers => true
  pod 'Kingfisher', '5.15.8', :modular_headers => true
  pod 'ModuleSample', :path => '../ModuleSample', :modular_headers => true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        if defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
        end

        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      elsif config.name == 'Release'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
      end

      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
